From oven/bun:alpine

WORKDIR /User/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./app/backend ./app/backend


COPY . .

RUN bun install
RUN bun run db:generate

EXPOSE 8080

CMD ["bun","run","start:backend"]
