FROM oven/bun:alpine


WORKDIR /user/src/app

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/websocket ./app/websocket


COPY . .

RUN npm install  

RUN bun install
RUN bun run db:generate
RUN bun run build



 

CMD ["bun","run","start:frontend"]
