From oven/bun:alpine

WORKDIR /User/src/app

ARG DATABASE_URL

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./app/websocket ./app/websocket


COPY . .

RUN bun install
RUN bun run db:generate
RUN DATABASE_URL=${DATABASE_URL} bun run build



 

CMD ["bun","run","start:frontend"]
